version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/sgrep-build:2.1
    steps:
      - checkout
      - run: eval $(opam env); ./configure -novisual && make depend && make

  test:
    docker:
      - image: returntocorp/sgrep-build:2.1
    environment:
        PFFF_HOME: /home/opam/project
    steps:
      - checkout
      - run: eval $(opam env); ./configure -novisual && make depend && make test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test